# Generated by Django 2.0 on 2019-04-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Movie_ename',
            field=models.CharField(db_column='m_ename', max_length=255, null=True, verbose_name='英文名称'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Movie_href',
            field=models.CharField(db_column='m_href', max_length=255, null=True, verbose_name='电影链接'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Movie_star',
            field=models.CharField(db_column='m_star', max_length=255, null=True, verbose_name='电影评分'),
        ),
    ]
