# Generated by Django 2.0 on 2019-04-26 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spider', '0002_auto_20190426_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Movie_ename',
        ),
    ]
