# Generated by Django 2.0 on 2019-04-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spider', '0003_remove_movie_movie_ename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_name', models.CharField(db_column='p_name', max_length=255, verbose_name='手机名称')),
                ('Mobile_price', models.CharField(db_column='p_price', max_length=255, null=True, verbose_name='手机价格')),
                ('Mobile_comment', models.CharField(db_column='p_comment', max_length=255, null=True, verbose_name='手机内容')),
            ],
            options={
                'db_table': 'jd_mobile',
            },
        ),
    ]
